// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWqoRUdvbJ4ctVGuOsiN_3aiSmuconf9k',
    appId: '1:437972859416:web:42e849e1c30a948ac2e16d',
    messagingSenderId: '437972859416',
    projectId: 'authorization-banking-app',
    authDomain: 'authorization-banking-app.firebaseapp.com',
    storageBucket: 'authorization-banking-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7bt9x0BueMoh8vlp6mGeNU1tjXRN6hQY',
    appId: '1:437972859416:android:cb60291ed658b16ac2e16d',
    messagingSenderId: '437972859416',
    projectId: 'authorization-banking-app',
    storageBucket: 'authorization-banking-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzvpHDWdpyKXcRRVPnwGZH2l1bOvSZMMU',
    appId: '1:437972859416:ios:3d752902bf9f6b9ac2e16d',
    messagingSenderId: '437972859416',
    projectId: 'authorization-banking-app',
    storageBucket: 'authorization-banking-app.appspot.com',
    iosClientId: '437972859416-6tabhmtv6p1k32f3huenh4jq86pmntna.apps.googleusercontent.com',
    iosBundleId: 'com.example.villageBankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzvpHDWdpyKXcRRVPnwGZH2l1bOvSZMMU',
    appId: '1:437972859416:ios:3d752902bf9f6b9ac2e16d',
    messagingSenderId: '437972859416',
    projectId: 'authorization-banking-app',
    storageBucket: 'authorization-banking-app.appspot.com',
    iosClientId: '437972859416-6tabhmtv6p1k32f3huenh4jq86pmntna.apps.googleusercontent.com',
    iosBundleId: 'com.example.villageBankingApp',
  );
}
